### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'input')

### ISSUE THREAD

**Issue by soosr** [GingerPrivacy/GingerWallet#24]
```
2024-06-01 17:56:41.086 [22] ERROR      PeriodicRunner.ExecuteAsync (114)       System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Version.Parse(String input)
   at WalletWasabi.WebClients.Wasabi.WasabiClient.GetVersionsAsync(CancellationToken cancel) in WalletWasabi\WebClients\Wasabi\WasabiClient.cs:line 199
   at WalletWasabi.WebClients.Wasabi.WasabiClient.CheckUpdatesAsync(CancellationToken cancel) in WalletWasabi\WebClients\Wasabi\WasabiClient.cs:line 204
   at WalletWasabi.Services.UpdateChecker.ActionAsync(CancellationToken cancel) in WalletWasabi\Services\UpdateChecker.cs:line 38
   at WalletWasabi.Bases.PeriodicRunner.ExecuteAsync(CancellationToken stoppingToken) in WalletWasabi\Bases\PeriodicRunner.cs:line 84

```

**Comment by soosr** [comment]
Its the `Ww2LegalDocumentsVersion` that is null here:

https://github.com/GingerPrivacy/GingerWallet/blob/592df1e3ffe6cf198778c76812e5d943832a140c/WalletWasabi/WebClients/Wasabi/WasabiClient.cs#L199

**Comment by soosr** [comment]
My master wasn't updated.
